miniprojet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic.base import RedirectView

from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authentification.urls')),
    url(r'^quiz/', include('quiz.urls')),
    path('', RedirectView.as_view(url='/auth/', permanent=True)),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import logout

from . import views

urlpatterns = [
    url(r'^$', views.index , name='index'),
    url(r'^create/$', views.create_view, name='create_view'),
    url(r'^(?P<exam_id>[0-9]+)/$', views.detail,name='detail'),
    url(r'^createQuest/$', views.createExam, name='createExam'),
    url(r'^(?P<question_id>[0-9]+)/modifOne/$', views.modifOne, name='modifOne'),
    url(r'^(?P<question_id>[0-9]+)/deleteQuest/$', views.deleteQuest, name='deleteQuest'),
    url(r'^(?P<question_id>[0-9]+)/modifmulti/$',views.modifmulti, name='modifmulti'),
    url(r'^(?P<question_id>[0-9]+)/modifFree/$',views.modifFree, name='modifFree'),
    url(r'^envoie/$', views.envoie, name='envoie'),
    url(r'^(?P<exam_id>[0-9]+)/deleteEXam/$', views.deleteExam, name='deleteEXam'),
    url(r'^(?P<exam_id>[0-9]+)/editExam/$', views.editExam, name='editExam'),
    url(r'^(?P<exam_id>[0-9]+)/addQuest/$', views.addQuest, name='addQuest'),
    url(r'^(?P<exam_id>[0-9]+)/passer/$', views.passer, name='passer'),
    url(r'^(?P<exam_id>[0-9]+)/passer/(?P<question_id>[0-9]+)$', views.passer2, name='passer2'),
    url(r'^(?P<exam_id>[0-9]+)/result/$', views.result, name='result'),
    url(r'^(?P<exam_id>[0-9]+)/certif/$', views.certif, name='certif'),
    url(r'^AddUser/$', views.addUser, name='addUser'),
    url(r'^listUsers/$', views.listUsers, name='listUsers'),
    url(r'^AddUser/InviteUser$', views.invitation, name='invitation'),
    url(r'^becameProf/$', views.becameProf, name='becameProf'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),

]

quiz/models.py
from django.contrib.auth.models import User
from django.db import models


class Exam(models.Model):
  
    name = models.CharField(max_length=64, verbose_name=u'Exam_name' ,default=" ")
    logo = models.ImageField(upload_to='logos',  null=True)
    description=models.CharField(max_length=600, verbose_name=u'Exam_descr' ,default=" ")
    category = models.CharField(max_length=200, verbose_name=u'category', default=" ")
    timer=models.IntegerField(default=0)
    mode = models.CharField(
        max_length=40,
        default='Training',
    )
    is_active = models.BooleanField(default=False)
    score = models.IntegerField(default=0)
    prof = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profes', default=1)

    def __str__(self):
        return self.name


class Question(models.Model):
    question_text = models.CharField(max_length=256, verbose_name=u'Question\'s text', default=" ")
    point=models.IntegerField(default=0)
    header_text = models.CharField(max_length=600, verbose_name=u'header\'s text', default=" ")
    footer_text = models.CharField(max_length=600, verbose_name=u'footer\'s text', default=" ")
    success_message = models.CharField(max_length=600, verbose_name=u'success\'s message', default=" ")
    fail_message = models.CharField(max_length=600, verbose_name=u'fail\'s message', default=" ")
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE,)

    def __str__(self):
        return "{content}".format(content=self.question_text)
class One_answer(models.Model):
    answer_variant=models.CharField(max_length=600, verbose_name=u'variant', default=" ")
    answer_description=models.CharField(max_length=600, verbose_name=u'description', default=" ")
    answer_point=models.IntegerField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    def __str__(self):
        return self.answer_variant
class Free_text(models.Model):
    answer_text=models.CharField(max_length=600, verbose_name=u'answer_text', default=" ")
    question = models.ForeignKey(Question, on_delete=models.CASCADE )
    def __str__(self):
        return self.answer_text

class MultiChoice(models.Model):
    multi_variant=models.CharField(max_length=600, verbose_name=u'variant', default=" ")
    multi_description=models.CharField(max_length=600, verbose_name=u'description', default=" ")
    choice_point=models.IntegerField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    def __str__(self):
        return self.multi_variant


class Reponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='Exam', default=1)
    one_answer = models.ForeignKey(One_answer, on_delete=models.CASCADE, related_name='One_answer', null=True)
    multichoice = models.ForeignKey(MultiChoice, on_delete=models.CASCADE, related_name='multi_choice_answer',
                                    null=True)
    free_text = models.CharField(max_length=1000, default='')
    score = models.IntegerField(default=0)


class studentClass(models.Model):
    professor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='prof', default=1)
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student', default=0)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='exam', default=0)
    email_invited = models.CharField(max_length=1000, default="")


class Invitation(models.Model):
    prof = models.ForeignKey(User, on_delete=models.CASCADE, related_name='professor', default=1)
    student = models.CharField(max_length=600, default=" ")
    exams = models.ForeignKey(Exam, on_delete=models.CASCADE, default=0)
    passed = models.BooleanField(default=False)

quiz/forms.py
from django.contrib.auth.models import User

from django.forms.widgets import RadioSelect, Textarea

class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list,
                                                   widget=RadioSelect)

quiz/views.py
from random import *

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.template import loader

from authentification.models import Profile
from .models import Question, Exam, One_answer, Free_text, MultiChoice, Reponse, studentClass, Invitation, User


@login_required
def logout(request):
    logout(request)
    return render(request, 'homepage/index.html')

def index(request):
    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
        if profile.is_professor == True:
            all_exams = Exam.objects.filter(prof=request.user)
            context = {
                'all_exams': all_exams,
            }
            return render(request, 'exams/index.html', context)
        else:
            my_template = 'exams/base.html'
            invite = studentClass.objects.filter(student=request.user)
            context = {
                'my_template': my_template,
                'invite': invite,
            }
            return render(request, 'exams/studentIndex.html', context)

    else:
        return render(request, 'homepage/index.html')


def create_view(request):
    return render(request, 'exams/createExam.html')


def detail(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    return render(request, 'exams/details.html', {'exam1': exam,
                                                  'exam1_id': exam_id, })


def createExam(request):
    if request.user.is_authenticated:
        if request.method == 'POST' and request.POST['examName']:
            examName = request.POST['examName']
            ExamDesc = request.POST['ExamDesc']
            category = request.POST['category']
            logo = request.FILES['logo']
            mode = request.POST['mode']
            timer = request.POST['timer']
            score = request.POST['score']

            exam = Exam()
            exam.name = examName
            exam.description = ExamDesc
            exam.category = category
            exam.logo = logo
            exam.mode = mode
            exam.timer = timer
            exam.score = score
            exam.prof = request.user
            exam.save()
            request.session['id'] = exam.id
            print(request.session['id'])

            context = {
                'exam_id': exam.id,
            }
            return render(request, 'exams/createQuest.html', context)


def editExam(request, exam_id):
    if request.user.is_authenticated:
        exam = get_object_or_404(Exam, pk=exam_id)
        if request.method == 'POST':
            exam.name = request.POST['examName']
            exam.description = request.POST['examDesc']
            exam.category = request.POST['category']
            exam.logo = request.FILES['logo']
            exam.timer = request.POST['timer']
            exam.score = request.POST['score']
            exam.mode = request.POST['mode']
            exam.save()
            return redirect('/quiz/')
        else:
            template = loader.get_template('exams/editExam.html')
            context = {
                'exam': exam,

            }
            return HttpResponse(template.render(context, request))


def deleteExam(request, exam_id):
    if request.user.is_authenticated:
        Exam.objects.filter(pk=exam_id).delete()
        return redirect('/quiz/')


def addQuest(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    if request.user.is_authenticated:
        if request.method == 'POST' and request.POST['Description']:
            question = Question()
            question.exam = exam
            question.question_text = request.POST['Description']
            question.footer_text = request.POST['Footer']
            question.header_text = request.POST['Header']
            question.success_message = request.POST['Success']
            question.fail_message = request.POST['Fail']
            question.point = request.POST['points']
            type_quest = request.POST['type']
            question.save()
            if type_quest == 'one':
                one1 = One_answer()
                one1.answer_description = request.POST['answer_description1']
                one1.answer_variant = request.POST['answer_variant1']
                one1.answer_point = request.POST['answer_points1']
                one1.question = question
                one1.save()
                one2 = One_answer()
                one2.answer_description = request.POST['answer_description2']
                one2.answer_variant = request.POST['answer_variant2']
                one2.answer_point = request.POST['answer_points2']
                one2.question = question
                one2.save()
                one3 = One_answer()
                one3.answer_description = request.POST['answer_description3']
                one3.answer_variant = request.POST['answer_variant3']
                one3.answer_point = request.POST['answer_points3']
                one3.question = question
                one3.save()
            if type_quest == 'multi':
                multi1 = MultiChoice()
                multi1.question = question
                multi1.multi_description = request.POST['answer_descriptionm1']
                multi1.multi_variant = request.POST['answer_variantm1']
                multi1.choice_point = request.POST['pointsm1']
                multi1.save()
                multi2 = MultiChoice()
                multi2.question = question
                multi2.multi_description = request.POST['answer_descriptionm2']
                multi2.multi_variant = request.POST['answer_variantm2']
                multi2.choice_point = request.POST['pointsm2']
                multi2.save()
                multi3 = MultiChoice()
                multi3.question = question
                multi3.multi_description = request.POST['answer_descriptionm3']
                multi3.multi_variant = request.POST['answer_variantm3']
                multi3.choice_point = request.POST['pointsm3']
                multi3.save()
            if type_quest == 'free':
                free = Free_text()
                free.question = question
                free.answer_text = request.POST['text']
                free.save()
                return redirect('/quiz/')
        else:
            template = loader.get_template('exams/addQuestion.html')
            context = {
                'exam': exam

            }

            return HttpResponse(template.render(context, request))


def modifOne(request, question_id):
    if request.user.is_authenticated:
        question = get_object_or_404(Question, pk=question_id)
        if request.method == 'POST':

            question.question_text = request.POST['Description']
            question.footer_text = request.POST['Footer']
            question.header_text = request.POST['Header']
            question.success_message = request.POST['Success']
            question.fail_message = request.POST['Fail']
            question.point = request.POST['points']
            question.save()
            i1 = request.POST['id1']
            i2 = request.POST['id2']
            i3 = request.POST['id3']
            onee1 = get_object_or_404(One_answer, pk=i1)
            onee1.answer_description = request.POST['answer_description1']
            onee1.answer_variant = request.POST['answer_variant1']
            onee1.answer_point = request.POST['answer_point1']
            onee1.question = question
            onee1.save()
            onee2 = get_object_or_404(One_answer, pk=i2)
            onee2.answer_description = request.POST['answer_description2']
            onee2.answer_variant = request.POST['answer_variant2']
            onee2.answer_point = request.POST['answer_point2']
            onee2.save()
            onee3 = get_object_or_404(One_answer, pk=i3)
            onee3.answer_description = request.POST['answer_description3']
            onee3.answer_variant = request.POST['answer_variant3']
            onee3.answer_point = request.POST['answer_point3']
            onee3.save()
            return redirect('/quiz/')
        else:
            template = loader.get_template('exams/ModifOneAnswer.html')
            context = {
                'question': question

            }
            return HttpResponse(template.render(context, request))


def modifmulti(request, question_id):
    if request.user.is_authenticated:
        question = get_object_or_404(Question, pk=question_id)
        if request.method == 'POST':

            question.question_text = request.POST['Description']
            question.footer_text = request.POST['Footer']
            question.header_text = request.POST['Header']
            question.success_message = request.POST['Success']
            question.fail_message = request.POST['Fail']
            question.point = request.POST['points']
            question.save()
            i1 = request.POST['id1']
            i2 = request.POST['id2']
            i3 = request.POST['id3']
            multi1 = get_object_or_404(MultiChoice, pk=i1)
            multi1.multi_description = request.POST['answer_description1']
            multi1.multi_variant = request.POST['answer_variant1']
            multi1.choice_point = request.POST['points1']
            multi1.question = question
            multi1.save()
            multi2 = get_object_or_404(MultiChoice, pk=i2)
            multi2.multi_description = request.POST['answer_description2']
            multi2.multi_variant = request.POST['answer_variant2']
            multi2.choice_point = request.POST['points2']
            multi2.save()
            multi3 = get_object_or_404(MultiChoice, pk=i3)
            multi3.multi_description = request.POST['answer_description3']
            multi3.multi_variant = request.POST['answer_variant3']

quiz/templates/exams/ExamQuest.html
{% extends 'exams/baseProfessor.html' %}

{% block title %}Quiz{% endblock %}

{% block content %}

<div class="col-lg-8">


    <div class="card">
        <div class="card-header">
            <h4>Exam {{examen.name}}</h4>
        </div>
        <div class="card-body">

            <form method="post" action="{{i}}" enctype="multipart/form-data">


                {%csrf_token%}
                <input type="hidden" value="{{question.id}}" name="id">

                {%if quest.multichoice_set.all %}
                <div class="col col-md-3"><label class=" form-control-label">{{quest.question_text}}</label></div>
                <div class="col col-md-9">
                    <div class="form-check">
                        {%for choix in quest.multichoice_set.all %}
                        <div class="radio">
                            <label for="{{choix.id}}" class="form-check-label ">
                                <input type="checkbox" name="radiosM" value="{{choix.id}}" class="form-check-input">{{choix.multi_variant}}
                            </label>
                        </div>

                        {%endfor%}

                    </div>
                </div>

                {%endif%}
                {%if quest.one_answer_set.all %}
                <div class="col col-md-3"><label class=" form-control-label">{{quest.question_text}}</label></div>
                <div class="col col-md-9">
                    <div class="form-check">
                        {%for choix in quest.one_answer_set.all %}
                        <div class="radio">
                            <label for="{{choix.id}}" class="form-check-label ">
                                <input type="radio" id="{{choix.id}}" name="radios" value="{{choix.id}}"
                                       class="form-check-input">{{choix.answer_variant}}
                            </label>
                        </div>

                        {%endfor%}
                        <a href="#{{question.id}}" class="btn btn-block ">{{forloop.counter}}</a>

                    </div>
                </div>

                {%endif%}
                {%if quest.free_text_set.all %}


                {%for choix in quest.free_text_set.all %}
                <div class="row form-group">
                    <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">{{quest.question_text}}</label>
                    </div>
                    <div class="col-12 col-md-9"><textarea name="text" id="textarea-input" rows="9"
                                                           placeholder="Content..." class="form-control"></textarea>
                    </div>

                </div>

                <br>{%endfor%}


                {%endif%}
                <center><input type="submit" value="submit" class="btn btn-danger" name="submit">
                </center>


            </form>
            <span id="time"></span>


        </div>
    </div>
</div>
<div class="col-lg-4">
    <div class="card">
        <div class="card-header">
            <strong>Questions</strong>
        </div>
        <div class="card-body">
            {% for qu in liste %}
            {% for index in bliste %}
            {% if forloop.counter == forloop.parentloop.counter %}
            {% if index %}
            <a href="{{qu}}" class="btn  btn-success" style="margin:3px">{{forloop.parentloop.counter}}</a>
            {% else %}
            <a href="{{qu}}" class="btn  btn-danger" style="margin:3px">{{forloop.parentloop.counter}}</a>
            {% endif%}
            {% endif %}
            {% endfor %}
            {%endfor%}

        </div>
    </div>
</div>
<center><a href="/quiz/{{examen_id}}/result" class="btn btn-block btn-primary">Finish</a></center>
<p id="demo"></p>


<script>
function startTimer(duration, display) {
var start = localStorage.getItem("start"),
diff,
minutes,
seconds;
if (start === null) {
start = Date.now();
localStorage.setItem("start", start);
}
function timer() {
// get the number of seconds that have elapsed since // startTimer() was called
diff = duration - (((Date.now() - start) / 1000) | 0);
// does the same job as parseInt truncates the float
minutes = (diff / 60) | 0;
seconds = (diff % 60) | 0;
minutes = minutes < 10 ? "0" + minutes : minutes;
seconds = seconds < 10 ? "0" + seconds : seconds;
display.textContent = minutes + ":" + seconds;
if (diff <= 0) {
// add one second so that the count down starts at the full duration
// example 05:00 not 04:59


start = Date.now() + 1000;
localStorage.clear();
document.location.href="/quiz/{{examen_id}}/result";

}
}
;
// we don't want to wait a full second before the timer starts
timer();
setInterval(timer, 1000);
}
window.onload = function () {
var thirtyMinutes = 60 * {{examen.timer}},
display = document.querySelector('#time');
startTimer(thirtyMinutes, display);
};


</script>

{% endblock %}

quiz/templates/exams/ExamQuestC.html
{% extends 'exams/baseProfessor.html' %}

{% block title %}Quiz{% endblock %}

{% block content %}

<div class="col-lg-8">


    <div class="card">
        <div class="card-header">
            <h4>Exam {{examen.name}}</h4>
        </div>
        <div class="card-body">

            <form method="post" action="{{i}}" enctype="multipart/form-data">


                {%csrf_token%}
                <input type="hidden" value="{{question.id}}" name="id">

                {%if quest.multichoice_set.all %}
                <div class="col col-md-3"><label class=" form-control-label">{{quest.question_text}}</label></div>
                <div class="col col-md-9">
                    <div class="form-check">
                        {%for choix in quest.multichoice_set.all %}
                        <div class="radio">
                            <label for="{{choix.id}}" class="form-check-label ">
                                <input type="checkbox" name="radiosM" value="{{choix.id}}" class="form-check-input">{{choix.multi_variant}}
                            </label>
                        </div>

                        {%endfor%}

                    </div>
                </div>

                {%endif%}
                {%if quest.one_answer_set.all %}
                <div class="col col-md-3"><label class=" form-control-label">{{quest.question_text}}</label></div>
                <div class="col col-md-9">
                    <div class="form-check">
                        {%for choix in quest.one_answer_set.all %}
                        <div class="radio">
                            <label for="{{choix.id}}" class="form-check-label ">
                                <input type="radio" id="{{choix.id}}" name="radios" value="{{choix.id}}"
                                       class="form-check-input">{{choix.answer_variant}}
                            </label>
                        </div>

                        {%endfor%}
                        <a href="#{{question.id}}" class="btn btn-block ">{{forloop.counter}}</a>

                    </div>
                </div>

                {%endif%}
                {%if quest.free_text_set.all %}


                {%for choix in quest.free_text_set.all %}
                <div class="row form-group">
                    <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">{{quest.question_text}}</label>
                    </div>
                    <div class="col-12 col-md-9"><textarea name="text1" id="textarea-input" rows="9"
                                                           placeholder="Content..." class="form-control"></textarea>
                    </div>

                </div>

                <br>{%endfor%}


                {%endif%}
                <center><input type="submit" value="submit" class="btn btn-danger" name="submit">
                </center>


            </form>
            <span id="time"></span>


        </div>
    </div>
</div>
<div class="col-lg-4">
    <div class="card">
        <div class="card-header">
            <strong>Questions</strong>
        </div>
        <div class="card-body">
            {% for qu in liste %}
            {% for index in bliste %}
            {% if forloop.counter == forloop.parentloop.counter %}
            {% if index %}
            <a href="{{qu}}" class="btn  btn-success" style="margin:3px">{{forloop.parentloop.counter}}</a>
            {% else %}
            <a href="{{qu}}" class="btn  btn-danger" style="margin:3px">{{forloop.parentloop.counter}}</a>
            {% endif%}
            {% endif %}
            {% endfor %}
            {%endfor%}

        </div>
    </div>

</div>
<center><a href="/quiz/{{examen_id}}/certif" class="btn btn-block btn-primary">Finish</a></center>
<span id="time"></span>
<p id="demo"></p>


<script>
function startTimer(duration, display) {
var start = localStorage.getItem("start"),
diff,
minutes,
seconds;
if (start === null) {
start = Date.now();
localStorage.setItem("start", start);
}
function timer() {
// get the number of seconds that have elapsed since // startTimer() was called
diff = duration - (((Date.now() - start) / 1000) | 0);
// does the same job as parseInt truncates the float
minutes = (diff / 60) | 0;
seconds = (diff % 60) | 0;
minutes = minutes < 10 ? "0" + minutes : minutes;
seconds = seconds < 10 ? "0" + seconds : seconds;
display.textContent = minutes + ":" + seconds;
if (diff <= 0) {
// add one second so that the count down starts at the full duration
// example 05:00 not 04:59


start = Date.now() + 1000;
localStorage.clear();
document.location.href="/quiz/{{examen_id}}/certif";

}
}
;
// we don't want to wait a full second before the timer starts
timer();
setInterval(timer, 1000);
}
window.onload = function () {
var thirtyMinutes = 60 * {{examen.timer}},
display = document.querySelector('#time');
startTimer(thirtyMinutes, display);
};


</script>

{% endblock %}

quiz/templates/exams/certif.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Certif</title>
</head>
<body>
<div style="width:800px; height:600px; padding:20px; text-align:center; border: 10px solid #787878">
    <div style="width:750px; height:550px; padding:20px; text-align:center; border: 5px solid #787878">
        <span style="font-size:50px; font-weight:bold">Certificate of Completion</span>
        <br><br>
        <span style="font-size:25px"><i>This is to certify that</i></span>
        <br><br>
        <span style="font-size:30px"><b>{{username}}</b></span><br/><br/>
        <span style="font-size:25px"><i>has completed the course</i></span> <br/><br/>
        <span style="font-size:30px">{{exam.name}}</span> <br/><br/>
        <span style="font-size:20px">with score of <b>{{score}}%</b></span> <br/><br/><br/><br/>
        <span style="font-size:25px"><i>dated</i></span><br>
        {% now "jS \o\f F,Y" %}
        <span style="font-size:30px"></span>
    </div>
</div>

</body>
</html>

quiz/templates/exams/invitation.html
{% extends 'exams/baseProfessor.html' %}

{% block title %}Quiz{% endblock %}

{% block content %}
<div class="container">
    <form method="post" action="#">
        {%csrf_token%}
        <div class="form-group shadow-textarea">
            <label for="exampleFormControlTextarea6">Send Invitation to:</label>
            <textarea name="mails" class="form-control z-depth-1" id="exampleFormControlTextarea6" rows="3"
                      placeholder="Write mails here...(';' between mails)"></textarea>
        </div>
        <label for="exampleFormControlTextarea6">To pass:</label>
        <input list="browsers" name="browser">
        <datalist id="browsers">
            {%for exam in exams%}
            <option value="{{exam.name}}">
                {%endfor%}

        </datalist>
        <input type="hidden" value="{{user.email}}" name="email">
        <br><br>
        <input type="submit" value="Invite" class="btn btn-success float-xl-right">
    </form>
</div>

{% endblock %}

quiz/templates/exams/listUsers.html
{% extends 'exams/baseProfessor.html' %}

{% block title %}Quiz{% endblock %}

{% block content %}

<div class="container">
    <h2>List of students</h2>
    <br>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Exams</th>

        </tr>
        </thead>
        <tbody>
        {%for stud in profiles%}
        <tr>
            <td><a href="/quiz/profile">{{stud.student.username}}</a></td>
            <td>{{stud.email_invited}}</td>
            <td>{{stud.exam}}</td>

        </tr>
        {%endfor%}
        </tbody>
    </table>

</div>

{% endblock %}

quiz/templates/exams/passerExam.html
{% extends 'exams/baseProfessor.html' %}

{% block title %}Quiz{% endblock %}

{% block content %}


<div class="card">
    <div class="card-header">
        <h4>Exam {{exam1.name}}</h4>
    </div>
    <div class="card-body">

        <div class="col-lg-8">
            <center><h1>Let's begin</h1></center>
        </div>
        <div class="col-lg-4">
            <a href="{{y}}" class="btn btn-block btn-success">begin</a>


        </div>

    </div>
</div>

{% endblock %}

quiz/templates/exams/validate.html
{% extends 'authentification/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">

    <h1 class="my-4">you have passe the following exam:
        <small>{{exam.titre }}</small>
    </h1>
    <div class="row">
        <div class="col-md-7">
            <a href="#">
                <img class="img-fluid rounded mb-3 mb-md-0" src="{{exam.logo}}" alt="">
            </a>
        </div>
        <div class="col-md-5">
            <h3>{{exam.titre}}</h3>
            <p>passe score : {{exam.total }}</p>
            <a class="btn btn-primary" href="/qcm/">retour</a>
        </div>
    </div>
    <hr>

    <!-- Page Heading -->


    <!-- Project One -->